import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InteractJS from "./interactjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello World Create Next App",
  description: "Generated by NEXT",
};

export default function RootLayout({
//   children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* children指定でディレクトリ内のtsxが表示される */}
        {/* {children} */}
        
        {/* InteractJSのコンポーネントを最初で呼び出す */}
        <InteractJS />
      </body>
    </html>
  );
}
